#!/bin/sh
# -------
# File:        android-devel-download
# Description: Download and install android developer sdk and tools
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

usage(){
	echo "$(basename "$0") {install|uninstall}" >&2
	exit 1
}

[ "$1" ] || usage

. /usr/share/android-development-tools/android-development-common
#REQ_URL="https://dl.google.com/android/studio/install/0.8.6/android-studio-bundle-135.1339820-linux.tgz"

# current ide
REQ_URL="https://dl.google.com/dl/android/studio/ide-zips/2.3.3.0/android-studio-ide-162.4069837-linux.zip"
#current SDK
#REQ_URL="https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip"
case "$1" in
	install)
		if aurex-cache get "$REQ_URL" ; then
			EXEC_FILE="$(aurex-cache file "$REQ_URL")"
			if [ "$EXEC_FILE" ] && [ -r "$EXEC_FILE" ] ; then
				echo "Extracting files"
				mkdir -p "$DEST_DIR"
				#tar -C "$DEST_DIR" -xzf "$EXEC_FILE"
				unzip "$EXEC_FILE" -d "$DEST_DIR"
				chmod -R +r "$DEST_DIR"
				find "$DEST_DIR" -type d -exec chmod +rx {} \;
				SDK_DIR="$(find "$DEST_DIR" -type d -name sdk)"
				ln -sf "$SDK_DIR" "$DEST_DIR/sdk"
			fi
		fi
		;;
	uninstall)
		rm -fr "$DEST_DIR"
		;;
	*)
		usage
		;;
esac

exit 0
